CE100 Algorithms and Programming II HW3: ce100_hw3_algo.File_Compression_Decompression.HuffmanTree_Class Class Reference
ce100_hw3_algo.File_Compression_Decompression.HuffmanTree_Class Class Reference
A class for creating a Huffman Tree.
Public Member Functions
void Build (string source)
Builds the Huffman Tree from the input string.
BitArray Encode (string source)
Encodes a string using a Huffman tree and returns the result as a BitArray.
string Decode (BitArray bits)
Decodes a BitArray using a Huffman tree and returns the decoded string.
bool IsLeaf (MinHNode node)
Checks if a given node is a leaf node
Public Attributes
Dictionary< char, int > Freq = new Dictionary<char, int>()
A dictionary containing the frequency of each character in the input string.
Properties
MinHNode Root [get, set]
The root node of the Huffman Tree.
Detailed Description
A class for creating a Huffman Tree.
Definition at line 166 of file ce100-hw3-algo-lib.cs.
Member Function Documentation
Build()
void ce100_hw3_algo.File_Compression_Decompression.HuffmanTree_Class.Build (string source)
Builds the Huffman Tree from the input string.
Parameters
source The input string to build the Huffman Tree from.
Definition at line 186 of file ce100-hw3-algo-lib.cs.
{
       foreach (char c in source) {
         if (!Freq.ContainsKey(c)) {
           Freq.Add(c, 0);
         }
         Freq[c]++;
       }
       foreach (KeyValuePair<char, int> pair in Freq) {
         nodes.Add(new MinHNode() {
           Items = pair.Key,
           freq = pair.Value
         });
       }
       while (nodes.Count > 1) {
         List<MinHNode> orderedNodes = nodes.OrderBy(node => node.freq).ToList();
         List<MinHNode> taken = orderedNodes.Take(2).ToList();
         MinHNode parent = new MinHNode() {
           Items = '*',
           freq = taken[0].freq + taken[1].freq,
           left = taken[0],
           right = taken[1]
         };
         nodes.Remove(taken[0]);
         nodes.Remove(taken[1]);
         nodes.Add(parent);
         this.Root = nodes.FirstOrDefault();
       }
     }
References ce100_hw3_algo.File_Compression_Decompression.MinHNode.freq, ce100_hw3_algo.File_Compression_Decompression.HuffmanTree_Class.Freq, and ce100_hw3_algo.File_Compression_Decompression.HuffmanTree_Class.Root.
Decode()
string ce100_hw3_algo.File_Compression_Decompression.HuffmanTree_Class.Decode (BitArray bits)
Decodes a BitArray using a Huffman tree and returns the decoded string.
Parameters
bits The BitArray to decode.
Returns
The decoded string.
Definition at line 241 of file ce100-hw3-algo-lib.cs.
{
       MinHNode currentN = this.Root;
       string decoded = "";
       foreach (bool bit in bits) {
         if (bit) {
           if (currentN.right != null) {
             currentN = currentN.right;
           }
         } else {
           if (currentN.left != null) {
             currentN = currentN.left;
           }
         }
         if (IsLeaf(currentN)) {
           decoded += currentN.Items;
           currentN = this.Root;
         }
       }
       return decoded;
     }
References ce100_hw3_algo.File_Compression_Decompression.HuffmanTree_Class.IsLeaf(), ce100_hw3_algo.File_Compression_Decompression.MinHNode.Items, ce100_hw3_algo.File_Compression_Decompression.MinHNode.left, ce100_hw3_algo.File_Compression_Decompression.MinHNode.right, and ce100_hw3_algo.File_Compression_Decompression.HuffmanTree_Class.Root.
Encode()
BitArray ce100_hw3_algo.File_Compression_Decompression.HuffmanTree_Class.Encode (string source)
Encodes a string using a Huffman tree and returns the result as a BitArray.
Parameters
source The string to encode.
Returns
A BitArray containing the encoded data.
Definition at line 223 of file ce100-hw3-algo-lib.cs.
{
       List<bool> encSrc = new List<bool>();
       for (int i = 0; i < source.Length; i++) {
         List<bool> encSymbol = this.Root.Transition(source[i], new List<bool>());
         encSrc.AddRange(encSymbol);
       }
       BitArray bits = new BitArray(encSrc.ToArray());
       return bits;
     }
References ce100_hw3_algo.File_Compression_Decompression.HuffmanTree_Class.Root, and ce100_hw3_algo.File_Compression_Decompression.MinHNode.Transition().
IsLeaf()
bool ce100_hw3_algo.File_Compression_Decompression.HuffmanTree_Class.IsLeaf (MinHNode node)
Checks if a given node is a leaf node
Parameters
node The node to check.
Returns
True if the node is a leaf node, false otherwise.
Definition at line 271 of file ce100-hw3-algo-lib.cs.
{
       return (node.left == null && node.right == null);
     }
References ce100_hw3_algo.File_Compression_Decompression.MinHNode.left, and ce100_hw3_algo.File_Compression_Decompression.MinHNode.right.
Referenced by ce100_hw3_algo.File_Compression_Decompression.HuffmanTree_Class.Decode().
Member Data Documentation
Freq
Dictionary<char, int> ce100_hw3_algo.File_Compression_Decompression.HuffmanTree_Class.Freq = new Dictionary<char, int>()
A dictionary containing the frequency of each character in the input string.
Definition at line 180 of file ce100-hw3-algo-lib.cs.
Referenced by ce100_hw3_algo.File_Compression_Decompression.HuffmanTree_Class.Build().
Property Documentation
Root
MinHNode ce100_hw3_algo.File_Compression_Decompression.HuffmanTree_Class.Root get set
The root node of the Huffman Tree.
Definition at line 172 of file ce100-hw3-algo-lib.cs.
{
       get;
       set;
     }
Referenced by ce100_hw3_algo.File_Compression_Decompression.HuffmanTree_Class.Build(), ce100_hw3_algo.File_Compression_Decompression.HuffmanTree_Class.Decode(), and ce100_hw3_algo.File_Compression_Decompression.HuffmanTree_Class.Encode().
The documentation for this class was generated from the following file:
ce100-hw3-algo-lib-cs/ce100-hw3-algo-lib.cs