CE100 Algorithms and Programming II HW3: ce100_hw3_algo.File_Compression_Decompression.MinHNode_Music Class Reference
ce100_hw3_algo.File_Compression_Decompression.MinHNode_Music Class Reference
A node in the minimum heap tree used to encode and decode music data.
Public Member Functions
List< bool > Transition_Music (byte? items, List< bool > data)
Recursively traverse the tree to generate a list of boolean values that represent the encoded bit stream of a given music symbol.
Properties
byte Items [get, set]
The byte value of this node, representing a music symbol.
int Freq [get, set]
The frequency of the music symbol.
MinHNode_Music left [get, set]
The left child node.
MinHNode_Music right [get, set]
The right child node.
Detailed Description
A node in the minimum heap tree used to encode and decode music data.
Definition at line 281 of file ce100-hw3-algo-lib.cs.
Member Function Documentation
Transition_Music()
List<bool> ce100_hw3_algo.File_Compression_Decompression.MinHNode_Music.Transition_Music (byte? items, List< bool > data)
Recursively traverse the tree to generate a list of boolean values that represent the encoded bit stream of a given music symbol.
Parameters
items The music symbol to encode.
data The bit stream generated so far.
Returns
A list of boolean values that represent the encoded bit stream of the given music symbol.
Definition at line 320 of file ce100-hw3-algo-lib.cs.
{
       if (left == null && right == null) {
         if (Items == items) {
           return data;
         } else {
           return null;
         }
       } else {
         List<bool> Left = null;
         List<bool> Right = null;
         if (left != null) {
           List<bool> leftP = new List<bool>();
           leftP.AddRange(data);
           leftP.Add(false);
           Left = left.Transition_Music(items, leftP);
         }
         if (right != null) {
           List<bool> rightP = new List<bool>();
           rightP.AddRange(data);
           rightP.Add(true);
           Right = right.Transition_Music(items, rightP);
         }
         if (Left != null) {
           return Left;
         } else {
           return Right;
         }
       }
     }
References ce100_hw3_algo.File_Compression_Decompression.MinHNode_Music.Items, ce100_hw3_algo.File_Compression_Decompression.MinHNode_Music.left, ce100_hw3_algo.File_Compression_Decompression.MinHNode_Music.right, and ce100_hw3_algo.File_Compression_Decompression.MinHNode_Music.Transition_Music().
Referenced by ce100_hw3_algo.File_Compression_Decompression.HuffmanTree_Class_Music.Encode(), and ce100_hw3_algo.File_Compression_Decompression.MinHNode_Music.Transition_Music().
Property Documentation
Freq
int ce100_hw3_algo.File_Compression_Decompression.MinHNode_Music.Freq get set
The frequency of the music symbol.
Definition at line 293 of file ce100-hw3-algo-lib.cs.
                     {
       get;
       set;
     }
Items
byte ce100_hw3_algo.File_Compression_Decompression.MinHNode_Music.Items get set
The byte value of this node, representing a music symbol.
Definition at line 285 of file ce100-hw3-algo-lib.cs.
                       {
       get;
       set;
     }
Referenced by ce100_hw3_algo.File_Compression_Decompression.MinHNode_Music.Transition_Music().
left
MinHNode_Music ce100_hw3_algo.File_Compression_Decompression.MinHNode_Music.left get set
The left child node.
Definition at line 301 of file ce100-hw3-algo-lib.cs.
{
       get;
       set;
     }
Referenced by ce100_hw3_algo.File_Compression_Decompression.HuffmanTree_Class_Music.IsLeaf(), and ce100_hw3_algo.File_Compression_Decompression.MinHNode_Music.Transition_Music().
right
MinHNode_Music ce100_hw3_algo.File_Compression_Decompression.MinHNode_Music.right get set
The right child node.
Definition at line 309 of file ce100-hw3-algo-lib.cs.
{
       get;
       set;
     }
Referenced by ce100_hw3_algo.File_Compression_Decompression.HuffmanTree_Class_Music.IsLeaf(), and ce100_hw3_algo.File_Compression_Decompression.MinHNode_Music.Transition_Music().
The documentation for this class was generated from the following file:
ce100-hw3-algo-lib-cs/ce100-hw3-algo-lib.cs