CE100 Algorithms and Programming II HW3: ce100_hw3_algo.File_Compression_Decompression.HuffmanTree_Class_Music Class Reference
ce100_hw3_algo.File_Compression_Decompression.HuffmanTree_Class_Music Class Reference
HuffmanTree_Class_Music class for building Huffman tree and encoding/decoding data using the tree.
Public Member Functions
void Build (byte[] source)
Builds a Huffman tree using the frequency of each byte in the input data.
BitArray Encode (byte[] source)
Encodes the input data using the Huffman tree.
byte[] Decode (BitArray bits)
Decodes a given bit array using a Huffman tree.
bool IsLeaf (MinHNode_Music node)
Checks if a given node is a leaf node.
Public Attributes
Dictionary< byte, int > Freq = new Dictionary<byte, int>()
Dictionary that stores the frequency of each byte in the input data.
Properties
MinHNode_Music Root [get, set]
Root node of the Huffman tree.
Detailed Description
HuffmanTree_Class_Music class for building Huffman tree and encoding/decoding data using the tree.
Definition at line 358 of file ce100-hw3-algo-lib.cs.
Member Function Documentation
Build()
void ce100_hw3_algo.File_Compression_Decompression.HuffmanTree_Class_Music.Build (byte[] source)
Builds a Huffman tree using the frequency of each byte in the input data.
Parameters
source Byte array containing the input data.
Definition at line 381 of file ce100-hw3-algo-lib.cs.
{
       for (int i = 0; i < source.Length; i++) {
         if (!Freq.ContainsKey(source[i])) {
           Freq.Add(source[i], 0);
         }
         Freq[source[i]]++;
       }
       foreach (KeyValuePair<byte, int> item in Freq) {
         nodes.Add(new MinHNode_Music() {
           Items = item.Key,
           Freq = item.Value
         });
       }
       while (nodes.Count > 1) {
         List<MinHNode_Music> orderedNodes = nodes.OrderBy(node => node.Freq).ToList<MinHNode_Music>();
         if (orderedNodes.Count >= 2) {
           List<MinHNode_Music> taken = orderedNodes.Take(2).ToList<MinHNode_Music>();
           MinHNode_Music parent = new MinHNode_Music() {
             Items = byte.MaxValue,
             Freq = taken[0].Freq + taken[1].Freq,
             left = taken[0],
             right = taken[1]
           };
           nodes.Remove(taken[0]);
           nodes.Remove(taken[1]);
           nodes.Add(parent);
         }
         this.Root = nodes.FirstOrDefault();
       }
     }
References ce100_hw3_algo.File_Compression_Decompression.HuffmanTree_Class_Music.Freq, and ce100_hw3_algo.File_Compression_Decompression.HuffmanTree_Class_Music.Root.
Decode()
byte [] ce100_hw3_algo.File_Compression_Decompression.HuffmanTree_Class_Music.Decode (BitArray bits)
Decodes a given bit array using a Huffman tree.
Parameters
bits The bit array to decode.
Returns
The decoded byte array.
Definition at line 439 of file ce100-hw3-algo-lib.cs.
{
       MinHNode_Music currentN = this.Root;
       List<byte> decoded = new List<byte>();
       foreach (bool bit in bits) {
         if (bit) {
           if (currentN.right != null) {
             currentN = currentN.right;
           }
         } else {
           if (currentN.left != null) {
             currentN = currentN.left;
           }
         }
         if (IsLeaf(currentN)) {
           decoded.Add(currentN.Items);
           currentN = this.Root;
         }
       }
       return decoded.ToArray();
     }
References ce100_hw3_algo.File_Compression_Decompression.HuffmanTree_Class_Music.IsLeaf(), and ce100_hw3_algo.File_Compression_Decompression.HuffmanTree_Class_Music.Root.
Encode()
BitArray ce100_hw3_algo.File_Compression_Decompression.HuffmanTree_Class_Music.Encode (byte[] source)
Encodes the input data using the Huffman tree.
Parameters
source Byte array containing the input data.
Returns
BitArray object containing the encoded data.
Definition at line 422 of file ce100-hw3-algo-lib.cs.
{
       List<bool> encSrc = new List<bool>();
       for (int i = 0; i < source.Length; i++) {
         List<bool> encSymbol = this.Root.Transition_Music(source[i], new List<bool>());
         encSrc.AddRange(encSymbol);
       }
       BitArray bits = new BitArray(encSrc.ToArray());
       return bits;
     }
References ce100_hw3_algo.File_Compression_Decompression.HuffmanTree_Class_Music.Root, and ce100_hw3_algo.File_Compression_Decompression.MinHNode_Music.Transition_Music().
IsLeaf()
bool ce100_hw3_algo.File_Compression_Decompression.HuffmanTree_Class_Music.IsLeaf (MinHNode_Music node)
Checks if a given node is a leaf node.
Parameters
node The node to check.
Returns
True if the node is a leaf node, false otherwise.
Definition at line 468 of file ce100-hw3-algo-lib.cs.
{
       return (node.left == null && node.right == null);
     }
References ce100_hw3_algo.File_Compression_Decompression.MinHNode_Music.left, and ce100_hw3_algo.File_Compression_Decompression.MinHNode_Music.right.
Referenced by ce100_hw3_algo.File_Compression_Decompression.HuffmanTree_Class_Music.Decode().
Member Data Documentation
Freq
Dictionary<byte, int> ce100_hw3_algo.File_Compression_Decompression.HuffmanTree_Class_Music.Freq = new Dictionary<byte, int>()
Dictionary that stores the frequency of each byte in the input data.
Definition at line 375 of file ce100-hw3-algo-lib.cs.
Referenced by ce100_hw3_algo.File_Compression_Decompression.HuffmanTree_Class_Music.Build().
Property Documentation
Root
MinHNode_Music ce100_hw3_algo.File_Compression_Decompression.HuffmanTree_Class_Music.Root get set
Root node of the Huffman tree.
Definition at line 367 of file ce100-hw3-algo-lib.cs.
{
       get;
       set;
     }
Referenced by ce100_hw3_algo.File_Compression_Decompression.HuffmanTree_Class_Music.Build(), ce100_hw3_algo.File_Compression_Decompression.HuffmanTree_Class_Music.Decode(), and ce100_hw3_algo.File_Compression_Decompression.HuffmanTree_Class_Music.Encode().
The documentation for this class was generated from the following file:
ce100-hw3-algo-lib-cs/ce100-hw3-algo-lib.cs